# Generated by Django 5.2.4 on 2025-07-08 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver'),
        ),
    ]
