# Generated by Django 5.2.4 on 2025-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_riderequest_assigned_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
