# Generated by Django 5.2.4 on 2025-07-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_riderequest_notes_riderequest_pickup_time'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cab_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cabtype')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
