# Generated by Django 5.2.4 on 2025-07-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_availablecab'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
