# Generated by Django 5.2.4 on 2025-07-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_riderequest_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='riderequest',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='estimated_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
