"""
Django base settings for GoodMan Safari Pro project.
Generated by structure automation script.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ------------------------------------------------
# 🔐 Security Settings
# ------------------------------------------------
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-*dummy-key-for-dev*')
DEBUG = False
ALLOWED_HOSTS = ['brymax_2.onrender.com', 'brymax_2.onrender.com', 'www.brymax_2.onrender.com']

# ------------------------------------------------
# 📦 Installed Applications
# ------------------------------------------------
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',  # Serve static files efficiently
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'apps.core',
    'apps.client',
    'apps.driver',
    'apps.payments',
    'apps.notifications',
    'apps.adminpanel',
]

# ------------------------------------------------
# ⚙️ Middleware Configuration
# ------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ------------------------------------------------
# 🔗 URL Configuration
# ------------------------------------------------
ROOT_URLCONF = 'config.urls'

# ------------------------------------------------
# 🧠 Templates
# ------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ------------------------------------------------
# 🔌 WSGI Application
# ------------------------------------------------
WSGI_APPLICATION = 'config.wsgi.application'

# ------------------------------------------------
# 🗄️ Database
# ------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ------------------------------------------------
# 🌍 Internationalization
# ------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------
# 🗂 Static Files
# ------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ------------------------------------------------
# 📁 Media Files
# ------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ------------------------------------------------
# 🔑 Authentication
# ------------------------------------------------
LOGIN_URL = '/login/'

# ------------------------------------------------
# 🆔 Primary Key Field Type
# ------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
