# Generated by Django 5.0.7 on 2025-10-25 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload main banner image (stored locally, max 100MB)', null=True, upload_to='uploads/banners/images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL for desktop view', null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Upload mobile banner image (stored locally, max 100MB)', null=True, upload_to='uploads/banners/mobile/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL for mobile view', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload featured image (stored locally, max 100MB)', null=True, upload_to='uploads/blog/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL for featured image', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional image file paths or URLs'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image (stored locally)', null=True, upload_to='uploads/images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video file (stored locally, up to 500MB)', null=True, upload_to='uploads/videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional local image paths or URLs'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image (stored locally, max 500MB)', null=True, upload_to='uploads/media/images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video file (stored locally, max 500MB)', null=True, upload_to='uploads/media/videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload category image (stored locally, max 100MB)', null=True, upload_to='uploads/tour_categories/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload main vehicle image (max 100MB)', null=True, upload_to='vehicles/%Y/%m/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
