# Generated by Django 5.0.7 on 2025-10-02 19:41

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Vehicle image', max_length=255, null=True, verbose_name='vehicle_image'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='accessibility_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, help_text='Accessibility features (wheelchair access, etc.)', size=None),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, help_text='Vehicle features (AC, WiFi, etc.)', size=None),
        ),
    ]
