# Generated by Django 6.0 on 2026-01-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'Exchange Rate', 'verbose_name_plural': 'Exchange Rates'},
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='usd_to_kes',
            field=models.DecimalField(decimal_places=4, help_text='Current USD to KES rate', max_digits=12),
        ),
    ]
