# Generated by Django 6.0 on 2026-01-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDestinationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_one_way', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.destination')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.vehicle')),
            ],
        ),
    ]
