# Generated by Django 5.0.7 on 2025-09-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pesapal_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
