# Generated by Django 5.0.7 on 2025-10-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_vehicle_image_alter_vehicle_accessibility_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='accessibility_features',
        ),
    ]
