# Generated by Django 5.0.7 on 2025-08-17 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_driver_booking_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='videos/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='is_airport_transfer',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='is_excursion',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='is_tour',
        ),
        migrations.AddField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_type',
            field=models.CharField(choices=[('TRANSFER', 'Airport Transfer'), ('EXCURSION', 'Excursion'), ('TOUR', 'Tour / Safari')], default='TOUR', max_length=20),
        ),
    ]
