# Generated by Django 5.0.7 on 2025-10-02 19:54

from django.db import migrations
import cloudinary.models

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_vehicle_accessibility_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                null=True,
                max_length=255,
                help_text='Vehicle image',
                verbose_name='vehicle_image'
            ),
        ),
    ]