# Generated by Django 6.0 on 2026-01-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_vehicledestinationprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicledestinationprice',
            options={'verbose_name': 'Destination Price', 'verbose_name_plural': 'Destination Prices'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_ksh',
        ),
        migrations.AlterUniqueTogether(
            name='vehicledestinationprice',
            unique_together={('vehicle', 'destination')},
        ),
        migrations.AddField(
            model_name='vehicledestinationprice',
            name='price_one_way_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in USD for one-way trip', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicledestinationprice',
            name='price_return_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in USD for return trip', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicledestinationprice',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_prices', to='bookings.destination'),
        ),
        migrations.AlterField(
            model_name='vehicledestinationprice',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_prices', to='bookings.vehicle'),
        ),
        migrations.RemoveField(
            model_name='vehicledestinationprice',
            name='price_one_way',
        ),
        migrations.RemoveField(
            model_name='vehicledestinationprice',
            name='price_return',
        ),
    ]
