# Generated by Django 6.0 on 2025-12-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price_ksh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price in Ksh (dynamic conversion to USD)', max_digits=12, null=True),
        ),
    ]
