# Generated by Django 5.0.7 on 2025-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_pesapal_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pesapal_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number used for mobile payments', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
