# Generated by Django 5.0.7 on 2025-10-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Vehicle features (AC, WiFi, etc.)', null=True),
        ),
    ]
