# Generated by Django 6.0 on 2025-12-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_vehicle_price_ksh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
    ]
