# Generated by Django 6.0 on 2025-12-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_vehicle_created_at_remove_vehicle_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_kes', models.DecimalField(decimal_places=2, default=16628.1, help_text='Current USD to KES exchange rate', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rate',
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_ksh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price in Ksh (converted from USD using admin-set rate)', max_digits=12, null=True),
        ),
    ]
