# Generated by Django 5.0.7 on 2025-10-03 09:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_vehicle_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='accessibility_features',
            field=models.JSONField(blank=True, default=list, help_text='Accessibility features (wheelchair access, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='External URL for vehicle image (alternative to upload)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload vehicle image', max_length=255, null=True, verbose_name='vehicle_image'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['fuel_type'], name='bookings_ve_fuel_ty_2da5e4_idx'),
        ),
    ]
