# Generated by Django 5.0.7 on 2025-09-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_payment_amount_paid_payment_method_payment_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email provided by guest user', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='Phone provided by guest user', max_length=20, null=True),
        ),
    ]
