# Generated by Django 5.0.7 on 2025-08-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_options_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
