# Generated by Django 5.0.7 on 2025-09-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_tour_image_alter_tour_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pesapal_reference',
            field=models.CharField(blank=True, help_text='Pesapal OrderTrackingId', max_length=255, null=True),
        ),
    ]
