# Generated by Django 5.0.7 on 2025-09-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_payment_pesapal_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='The confirmation code from Pesapal/M-Pesa email', max_length=100, null=True),
        ),
    ]
