# Generated by Django 5.0.7 on 2025-09-17 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_payment_confirmation_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_city',
            field=models.CharField(blank=True, help_text='Billing city or town.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_country_code',
            field=models.CharField(blank=True, default='KE', help_text='Billing country code (ISO 3166-1 alpha-3).', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_line1',
            field=models.CharField(blank=True, help_text='Billing street address (line 1).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_line2',
            field=models.CharField(blank=True, help_text='Billing street address (line 2).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_postal_code',
            field=models.CharField(blank=True, help_text='Billing postal / ZIP code.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_state',
            field=models.CharField(blank=True, help_text='Billing state or region.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='guest_full_name',
            field=models.CharField(blank=True, help_text='Full name entered by guest during checkout.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='travel_date',
            field=models.DateField(blank=True, help_text='Date of travel as selected by the guest.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated total amount due (based on guests, days, rates).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount actually paid (returned by the gateway).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(blank=True, help_text='Link to a booking if this is a booking payment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='Confirmation code returned by the gateway/email.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created at this timestamp.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KES', help_text='Currency code for this payment.', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, help_text='Free-form description or notes.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email address entered by guest during checkout.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='Phone number entered by guest during checkout.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MPESA', 'M-PESA'), ('PESAPAL', 'Pesapal'), ('PAYPAL', 'PayPal'), ('CARD', 'Card Payment'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='MPESA', help_text='The payment method selected by the guest.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateTimeField(blank=True, help_text='Datetime when payment was confirmed.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pesapal_reference',
            field=models.CharField(blank=True, help_text='Pesapal OrderTrackingId.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone used for mobile payments (e.g. M-Pesa).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-PESA'), ('PESAPAL', 'Pesapal'), ('PAYPAL', 'PayPal'), ('CARD', 'Card Payment'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='PESAPAL', help_text='The payment gateway (Pesapal or M-Pesa).', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Full JSON response from the payment gateway.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Merchant reference for this transaction.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current status of the payment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='Link to a tour if this is a direct tour payment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.tour'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID returned by the gateway.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated at this timestamp.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Select a user if this payment is by a registered customer.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
