# Generated by Django 5.0.7 on 2025-09-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_payment_billing_city_payment_billing_country_code_and_more'),
    ]

    operations = [
    ]
