# Generated by Django 5.0.7 on 2025-09-17 10:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_reset_failed_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing_line2',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated total amount due.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount actually paid (returned by the gateway).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_city',
            field=models.CharField(default='Nairobi', help_text='Billing city or town.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_country_code',
            field=models.CharField(default='KE', help_text='Billing country code (ISO 3166-1 alpha-3).', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_line1',
            field=models.CharField(default='Nairobi', help_text='Billing street address (line 1).', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_postal_code',
            field=models.CharField(default='00100', help_text='Billing postal / ZIP code.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_state',
            field=models.CharField(default='Nairobi', help_text='Billing state or region.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmation_code',
            field=models.CharField(default='', help_text='Confirmation code returned by the gateway.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KES', help_text='Currency code.', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(default='Payment for Tour', help_text='Free-form description or notes.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pesapal_reference',
            field=models.CharField(default='', help_text='Pesapal OrderTrackingId.', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='', help_text='Phone used for mobile payments.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-PESA'), ('PESAPAL', 'Pesapal'), ('PAYPAL', 'PayPal'), ('CARD', 'Card Payment'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='PESAPAL', help_text='The payment gateway.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(db_index=True, default='', help_text='Merchant reference for this transaction.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='', help_text='Transaction ID returned by the gateway.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='travel_date',
            field=models.DateField(default=datetime.date(2025, 9, 17), help_text='Date of travel as selected by the guest.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Registered user (if logged in).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
