# Generated by Django 5.0.7 on 2025-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_remove_payment_billing_line2_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='adults',
            field=models.PositiveIntegerField(default=1, help_text='Number of adults.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='children',
            field=models.PositiveIntegerField(default=0, help_text='Number of children.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='days',
            field=models.PositiveIntegerField(default=1, help_text='Number of travel days.'),
        ),
    ]
