# Generated by Django 5.0.7 on 2025-09-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_payment_adults_payment_children_payment_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='children',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='days',
        ),
        migrations.AlterField(
            model_name='booking',
            name='pesapal_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_city',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_country_code',
            field=models.CharField(default='KE', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_line1',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_postal_code',
            field=models.CharField(default='00100', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_state',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(blank=True, help_text='Each booking must have one Payment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmation_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(default='Payment for Tour'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='guest_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MPESA', 'M-PESA'), ('PESAPAL', 'Pesapal'), ('PAYPAL', 'PayPal'), ('CARD', 'Card Payment'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='PESAPAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pesapal_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-PESA'), ('PESAPAL', 'Pesapal'), ('PAYPAL', 'PayPal'), ('CARD', 'Card Payment'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='PESAPAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.tour'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='travel_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
