# Generated by Django 5.0.7 on 2025-09-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_remove_payment_adults_remove_payment_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pesapal_reference',
        ),
        migrations.AlterField(
            model_name='payment',
            name='pesapal_reference',
            field=models.CharField(blank=True, help_text='Pesapal OrderTrackingId', max_length=255, null=True, unique=True),
        ),
    ]
