# Generated by Django 5.0.7 on 2025-09-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_remove_booking_pesapal_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pesapal_reference',
            field=models.CharField(blank=True, help_text='Pesapal OrderTrackingId', max_length=255, null=True),
        ),
    ]
