# Generated by Django 5.0.7 on 2025-09-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_payment_pesapal_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
