# Generated by Django 5.0.7 on 2025-09-18 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_payment_adults_payment_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmation_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pesapal_reference',
            field=models.CharField(blank=True, help_text='Pesapal OrderTrackingId for tracking payments', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
