# Generated by Django 5.0.7 on 2025-09-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_payment_days_alter_payment_confirmation_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pesapal_reference',
            new_name='pesapal_tracking_id',
        ),
    ]
