# Generated by Django 5.0.7 on 2025-09-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_rename_pesapal_reference_payment_pesapal_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, help_text='Unique session identifier for this payment attempt', max_length=255, null=True),
        ),
    ]
