# Generated by Django 5.0.7 on 2025-09-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_payment_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pesapal_tracking_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='session_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='access_code',
            field=models.CharField(blank=True, help_text='Paystack access code for transaction verification', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='authorization_code',
            field=models.CharField(blank=True, default='', help_text='Paystack authorization code for recurring payments', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_transaction_id',
            field=models.CharField(blank=True, help_text='Paystack transaction ID for tracking payments', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MPESA', 'M-PESA'), ('PAYSTACK', 'Paystack'), ('PAYPAL', 'PayPal'), ('CARD', 'Card Payment'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='PAYSTACK', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-PESA'), ('PAYSTACK', 'Paystack'), ('PAYPAL', 'PayPal'), ('CARD', 'Card Payment'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='PAYSTACK', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(db_index=True, default='', help_text='Paystack transaction reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', help_text='Internal transaction ID', max_length=100),
        ),
    ]
