# Generated by Django 5.0.7 on 2025-09-21 19:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_created_at_booking_status_booking_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at'], 'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['name'], 'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether payment has been completed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Preferred pickup time'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Whether this message has been resolved'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='normalized_phone',
            field=models.CharField(blank=True, help_text='E.164 formatted phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of name', max_length=170, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='normalized_phone',
            field=models.CharField(blank=True, help_text='E.164 formatted phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Average customer rating (0.0-5.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='normalized_guest_phone',
            field=models.CharField(blank=True, help_text='E.164 formatted phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('ADVENTURE', 'Adventure Safari'), ('WILDLIFE', 'Wildlife Safari'), ('CULTURAL', 'Cultural Tour'), ('BEACH', 'Beach Holiday'), ('MOUNTAIN', 'Mountain Climbing')], default='WILDLIFE', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('CHALLENGING', 'Challenging')], default='EASY', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='featured',
            field=models.BooleanField(default=False, help_text='Whether to feature this tour on homepage'),
        ),
        migrations.AddField(
            model_name='tour',
            name='max_group_size',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of people per tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='min_group_size',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of people per tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance traveled in kilometers', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('DESTINATION', 'Destination Video'), ('TESTIMONIAL', 'Customer Testimonial'), ('ACTIVITY', 'Tour Activity'), ('PROMOTION', 'Promotional Video')], default='DESTINATION', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=275, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='available',
            field=models.BooleanField(default=True, help_text='Whether this tour is currently bookable'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary',
            field=models.TextField(blank=True, help_text='Day-by-day itinerary', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='bookings_pa_user_id_d4eeac_idx'),
        ),
    ]
