# Generated by Django 5.0.7 on 2025-09-22 17:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_payment_customer_id_payment_failure_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_passengers',
            new_name='num_adults',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='customer_id',
            new_name='refund_reference',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(default='BRYTECH', help_text='Unique booking reference', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_infants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, help_text='Return date for multi-day trips', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_time',
            field=models.TimeField(blank=True, help_text='Return time for multi-day trips', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.tour'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='VIP customer status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this destination on homepage'),
        ),
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Driver has been verified by admin'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_type',
            field=models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('COMMERCIAL', 'Commercial')], default='COMMERCIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_trips',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_capacity',
            field=models.PositiveIntegerField(default=4, help_text='Vehicle passenger capacity'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer associated with this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_point',
            field=models.CharField(default='Nairobi', help_text='Tour departure location', max_length=200),
        ),
        migrations.AddField(
            model_name='tour',
            name='destinations_visited',
            field=models.TextField(blank=True, help_text='List of destinations visited', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discounted price if applicable', max_digits=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_nights',
            field=models.PositiveIntegerField(default=0, help_text='Number of nights for the tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='exclusions',
            field=models.TextField(blank=True, help_text="What's not included in the tour", null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional image URLs'),
        ),
        migrations.AddField(
            model_name='tour',
            name='highlights',
            field=models.TextField(blank=True, help_text='Key highlights of the tour', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='inclusions',
            field=models.TextField(blank=True, help_text="What's included in the tour", null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Whether this is a popular tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='max_advance_booking_days',
            field=models.PositiveIntegerField(default=365, help_text='Maximum days in advance for booking'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short catchy phrase for the tour', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='trip',
            name='customer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='customer_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Customer rating (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel consumed in liters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='bookings.destination'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, help_text='Video duration', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='bookings.tour'),
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partial Refund')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('ADVENTURE', 'Adventure Safari'), ('WILDLIFE', 'Wildlife Safari'), ('CULTURAL', 'Cultural Tour'), ('BEACH', 'Beach Holiday'), ('MOUNTAIN', 'Mountain Climbing'), ('CITY', 'City Tour')], default='WILDLIFE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('CHALLENGING', 'Challenging'), ('EXTREME', 'Extreme')], default='EASY', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('DESTINATION', 'Destination Video'), ('TESTIMONIAL', 'Customer Testimonial'), ('ACTIVITY', 'Tour Activity'), ('PROMOTION', 'Promotional Video'), ('DRIVER', 'Driver Profile')], default='DESTINATION', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Review has been verified as genuine')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.driver')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.tour')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'booking')},
            },
        ),
    ]
