# Generated by Django 5.0.7 on 2025-09-22 17:37

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_rename_num_passengers_booking_num_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(default=bookings.models.generate_booking_reference, editable=False, max_length=50, unique=True),
        ),
    ]
