# Generated by Django 5.0.7 on 2025-09-22 18:34

import bookings.models
import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_alter_booking_booking_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the booking was made'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(default=bookings.models.generate_booking_reference, editable=False, help_text='Unique booking reference', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('TRANSFER', 'Airport Transfer'), ('EXCURSION', 'Excursion'), ('TOUR', 'Tour / Safari')], help_text='Type of booking', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(help_text='Customer who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Destination for the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver assigned to this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.driver'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff_location',
            field=models.CharField(blank=True, help_text='Drop-off location', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Whether the booking has been cancelled'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the booking', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_adults',
            field=models.PositiveIntegerField(default=1, help_text='Number of adult passengers'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(default=0, help_text='Number of child passengers'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_infants',
            field=models.PositiveIntegerField(default=0, help_text='Number of infant passengers'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Pickup location', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Special customer requests', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', help_text='Current status of the booking', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total price for the booking', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='Tour for the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.tour'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(help_text='Date of travel'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User this message is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='Email address of the sender', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='Message content'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Name of the person sending the message', max_length=150),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of the sender', max_length=20, null=True, validators=[bookings.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level of the message', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the message was resolved', null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User who resolved this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(help_text='Subject of the message', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Customer's date of birth", null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text="Customer's email address", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(help_text="Customer's first name", max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], help_text="Customer's gender", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this customer account is active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(help_text="Customer's last name", max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, help_text="Customer's nationality", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(blank=True, help_text="Customer's passport number", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(help_text="Customer's phone number", max_length=20, validators=[bookings.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, default='No description available', help_text='Detailed description of the destination'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_type',
            field=models.CharField(choices=[('TRANSFER', 'Airport Transfer'), ('EXCURSION', 'Excursion'), ('TOUR', 'Tour / Safari')], default='TOUR', help_text='Type of destination', max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary image for the destination', null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL as fallback', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this destination is currently available'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(blank=True, default='Unknown location', help_text='Physical location of the destination', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(help_text='Name of the destination', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per person in KES', max_digits=10),
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', help_text='URL-friendly version of name', max_length=170, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='video',
            field=models.FileField(blank=True, help_text='Promotional video for the destination', null=True, upload_to='destinations/videos/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='available',
            field=models.BooleanField(default=True, help_text='Whether the driver is currently available'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='bio',
            field=models.TextField(blank=True, help_text="Driver's professional bio", null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of driving experience'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this driver account is active'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, help_text='License expiry date', null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(help_text="Driver's license number", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_type',
            field=models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('COMMERCIAL', 'Commercial')], default='COMMERCIAL', help_text='Type of driving license', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(help_text="Driver's full name", max_length=150),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(help_text="Driver's phone number", max_length=20, validators=[bookings.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Driver's profile picture", null=True, upload_to='drivers/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings from all trips', max_digits=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='total_trips',
            field=models.PositiveIntegerField(default=0, help_text='Total number of completed trips'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked user account for the driver', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.CharField(blank=True, help_text='Vehicle model', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_plate',
            field=models.CharField(blank=True, help_text='Vehicle license plate number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='adults',
            field=models.PositiveIntegerField(default=1, help_text='Number of adult passengers'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Payment amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount actually paid', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_city',
            field=models.CharField(default='Nairobi', help_text='Billing city', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_country_code',
            field=models.CharField(default='KE', help_text='Billing country code (ISO 3166-1 alpha-3)', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_line1',
            field=models.CharField(default='Nairobi', help_text='Billing address line 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_postal_code',
            field=models.CharField(default='00100', help_text='Billing postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_state',
            field=models.CharField(default='Nairobi', help_text='Billing state/county', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(blank=True, help_text='Booking associated with this payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='children',
            field=models.PositiveIntegerField(default=0, help_text='Number of child passengers'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KES', help_text='Payment currency', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days for the booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(default='Payment for Tour', help_text='Payment description'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason for payment failure', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='guest_email',
            field=models.EmailField(blank=True, help_text="Guest's email address", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='guest_full_name',
            field=models.CharField(blank=True, help_text="Guest's full name", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='guest_phone',
            field=models.CharField(blank=True, help_text="Guest's phone number", max_length=20, null=True, validators=[bookings.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which payment was made', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MPESA', 'M-PESA'), ('PAYSTACK', 'Paystack'), ('PAYPAL', 'PayPal'), ('CARD', 'Card Payment'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='PAYSTACK', help_text='Payment method', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateTimeField(blank=True, help_text='When the payment was completed', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_channel',
            field=models.CharField(blank=True, help_text='Payment channel used', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number for mobile payments', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-PESA'), ('PAYSTACK', 'Paystack'), ('PAYPAL', 'PayPal'), ('CARD', 'Card Payment'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='PAYSTACK', help_text='Payment provider', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Raw response from payment provider', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount refunded', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Reason for refund', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_reference',
            field=models.CharField(blank=True, help_text='Reference for the refund', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refunded_on',
            field=models.DateTimeField(blank=True, help_text='When the refund was processed', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partial Refund')], default='PENDING', help_text='Payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='Tour associated with this payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.tour'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of travel'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Registered user (if logged in)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, help_text='When the webhook was received', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='webhook_verified',
            field=models.BooleanField(default=False, help_text='Whether the webhook has been verified'),
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(help_text='Booking associated with this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='Review comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(help_text='Customer who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.customer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver being reviewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.driver'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this review is public'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Rating given (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(help_text='Review title', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='Tour being reviewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.tour'),
        ),
        migrations.AlterField(
            model_name='review',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the review was verified', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the tour was approved', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this tour', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('ADVENTURE', 'Adventure Safari'), ('WILDLIFE', 'Wildlife Safari'), ('CULTURAL', 'Cultural Tour'), ('BEACH', 'Beach Holiday'), ('MOUNTAIN', 'Mountain Climbing'), ('CITY', 'City Tour')], default='WILDLIFE', help_text='Category of the tour', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this tour', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(default='No description available', help_text='Detailed description of the destination'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('CHALLENGING', 'Challenging'), ('EXTREME', 'Extreme')], default='EASY', help_text='Difficulty level of the tour', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Duration in days'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Primary tour image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL as fallback', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the tour has been approved'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per person in KES', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, default=1, help_text='URL-friendly version of title', max_length=220, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(help_text='Tour title', max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Tour promotional video', max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Booking associated with this trip', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='customer_feedback',
            field=models.TextField(blank=True, help_text='Customer feedback about the trip', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(help_text='Date of the trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(help_text='Trip destination', max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(help_text='Driver who completed the trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bookings.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Earnings from the trip', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Trip end time', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the trip', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Trip start time'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', help_text='Current status of the trip', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('DESTINATION', 'Destination Video'), ('TESTIMONIAL', 'Customer Testimonial'), ('ACTIVITY', 'Tour Activity'), ('PROMOTION', 'Promotional Video'), ('DRIVER', 'Driver Profile')], default='DESTINATION', help_text='Video category', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='Video description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Destination this video is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='bookings.destination'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(help_text='Video file', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this video is active'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether to feature this video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for paid videos', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', help_text='URL-friendly version of title', max_length=275, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Video thumbnail image', null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='Video title', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='Tour this video is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='bookings.tour'),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the video has been viewed'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_bo_booking_8a7545_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['travel_date'], name='bookings_bo_travel__83d735_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'travel_date'], name='bookings_bo_custome_186a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['priority'], name='bookings_co_priorit_b4ac58_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_resolved'], name='bookings_co_is_reso_80e63b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['assigned_to'], name='bookings_co_assigne_41fd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'status'], name='bookings_pa_custome_4825f3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='bookings_re_rating_a9b587_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_public'], name='bookings_re_is_publ_70a99a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified'], name='bookings_re_is_veri_9c3d62_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tour', 'rating'], name='bookings_re_tour_id_a69bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['driver', 'rating'], name='bookings_re_driver__7921fd_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['category'], name='bookings_to_categor_015e22_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['difficulty'], name='bookings_to_difficu_cde77a_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_popular'], name='bookings_to_is_popu_1fd2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'date'], name='bookings_tr_driver__31c45f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='bookings_tr_status_491e53_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['date'], name='bookings_tr_date_8257ad_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category'], name='bookings_vi_categor_3d168d_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_featured'], name='bookings_vi_is_feat_093d82_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['view_count'], name='bookings_vi_view_co_5d688b_idx'),
        ),
    ]
